name: Build and Test the Shopify App

on:
  push:
    branches: [ "master", "main", "leo" ]

permissions:
  contents: read

jobs:
  frontend:
    uses: your-org/share-workflow/.github/workflows/app-py-frontend-ci.yml@main
    secrets:
      SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
  backend:
    uses: your-org/share-workflow/.github/workflows/app-py-backend-ci.yml@main
    with:
      python-versions: '[ "3.10", "3.11", "3.12" ]'
      backend-path: "backend"
      requirements-file: "backend/requirements/dev.txt"

# extra tests for extension
#  extensions:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v5
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v5.0.0
#        with:
#          node-version: "22.x"
#          cache: "yarn"
#
#      - name: Check Cart Transformer
#        run: |
#          cd extensions/cart-transformer
#          yarn install
#          yarn typegen
#          yarn test run