"""Initial Database

Revision ID: 3d1b6925999f
Revises: 
Create Date: 2023-09-11 10:51:57.007984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1b6925999f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.String(length=2048), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_key'), ['key'], unique=False)

    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('webhook_id', sa.BigInteger(), nullable=True, comment='Webhook ID'),
    sa.Column('target', sa.String(length=24), nullable=True, comment='Action Target'),
    sa.Column('action', sa.String(length=24), nullable=True, comment='Action'),
    sa.Column('data', sa.Text(length=64000), nullable=True, comment='JSON string -> 64kb medium text for MYSQL/MariaDB'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index('webhook_event_id', ['store_id', 'webhook_id', 'target'], unique=False)
        batch_op.create_index('webhook_target', ['store_id', 'target', 'action', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index('store_webhook')

    op.drop_table('webhooks')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_key'))

    op.drop_table('stores')
    # ### end Alembic commands ###
