# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Custom App name"
client_id = "d72f74c1687310e"
application_url = "https://merely-wyoming-genome-advances.trycloudflare.com"
embedded = true
web_directories = [ "frontend/admin", "backend" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,read_shipping,write_shipping"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://merely-wyoming-genome-advances.trycloudflare.com/proxy/callback",
  "https://merely-wyoming-genome-advances.trycloudflare.com/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pocket-square-sandbox.myshopify.com"
